# Lua is compiled into the executable; no system interpreter or runtime DLL.
set(ENGINE_LUA_ROOT "${CMAKE_SOURCE_DIR}/external/lua/lua-5.4.8" CACHE PATH "Lua source directory")
set(ENGINE_SOL_ROOT "${CMAKE_SOURCE_DIR}/external/sol2/sol2-3.3.1" CACHE PATH "sol2 source directory")
if(NOT EXISTS "${ENGINE_LUA_ROOT}/src/lua.h" OR NOT EXISTS "${ENGINE_SOL_ROOT}/include/sol/sol.hpp")
    message(FATAL_ERROR "Run powershell -ExecutionPolicy Bypass -File tools/setup_lua.ps1 first")
endif()
file(GLOB LUA_SOURCES CONFIGURE_DEPENDS "${ENGINE_LUA_ROOT}/src/*.c")
list(FILTER LUA_SOURCES EXCLUDE REGEX "/(lua|luac)\\.c$")
add_library(EngineLua STATIC ${LUA_SOURCES})
target_include_directories(EngineLua SYSTEM PUBLIC "${ENGINE_LUA_ROOT}/src" "${ENGINE_SOL_ROOT}/include")
target_compile_definitions(EngineLua PUBLIC SOL_ALL_SAFETIES_ON=1)
if(UNIX)
    target_compile_definitions(EngineLua PRIVATE LUA_USE_POSIX)
    target_link_libraries(EngineLua PUBLIC m ${CMAKE_DL_LIBS})
endif()
